# App Info
ios_app_id                                : 1347742014                              # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Manage the GPS location info of your photos in a few clicks or delete it in EXIF to protect your privacy.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nikolay Fiantsev                               
your_link                                 :                     
your_city                                 :                               
email_address                             : photomapperapp@gmail.com
facebook_username                         : NikolayFiantsev                                     
instagram_username                        : 
twitter_username                          : bigmotor
github_username                           : bigMOTOR
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Made for iOS Photos
    description                           : PhotoMapper is build to updates location info in your iOS Photo Library accross all your devices via sync.  
    fontawesome_icon_name                 : camera

  - title                                 : GPS tags always correct and never missed
    description                           : Easily add or modify location info of your photos in the iOS library with simple placing pin on map. Never missed it in case of DSLR usage or by any other reason. Since now it will be always correct and never missed.
    fontawesome_icon_name                 : map-marker
    
  - title                                 : Protect your privacy by erased location
    description                           : Prepare photos for social sharing with erased GPS location info in EXIF. Keep the original photo for you and create a copy without any mark of the location info (geotagging) in EXIF metadata for sharing pupose with reinforce of your privacy.
    fontawesome_icon_name                 : user-secret

  - title                                 : Batch photo edition
    description                           : Edit multiple photos in a few clicks the fast and easy way. Forget about single selection.
    fontawesome_icon_name                 : images

  - title                                 : Video Support
    description                           : PhotoMapper perfectly works with video in your iOS Photos library.
    fontawesome_icon_name                 : play-circle

  - title                                 : Find all photo with missed location
    description                           : Easily find all photos without location in one click.
    fontawesome_icon_name                 : search

  - title                                 : Universal iOS app
    description                           : It's a universal app, which you buy once and can use on all your iOS devices (iPhone, iPad, iPod Touch).
    fontawesome_icon_name                 : dollar-sign

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
